### PR TITLE
Fix for issue #258

### PR DESCRIPTION
**Pull request by samid737**
This PR changes

* Nothing, it's a bug fix

Describe the changes below:

Fix for issue #258 by applying the rotation first when changing a shape , then draw it via debugBody.draw(). The bug seems fixed (tested with all shapes), but its kind of a hack solution I guess..

### CODE REVIEW

**Comment by samme** [comment]
Did you test it?

**Comment by samid737** [comment]
Hi samme,

I have updated my commit, it turned out not to work for setCircle and setCapsule (for the capsule it locally rotates the child shapes too). I have a new commit that works for pretty much all shapes. Here is an example:

prior fix/hack:
https://codepen.io/pen?template=MoPYrg

after fix/hack:

http://54.87.189.59/bug258/

It seems to work this way?

**Comment by samid737** [comment]
https://github.com/photonstorm/phaser-ce/pull/279/commits/cfc7f95f32a32a2c0c246dc41af9aacef3159870

what I was trying to commit/show.

**Comment by goldfire** [comment]
This change seems to reset the rotation of the body to 0 whenever a shape is added to the body. Is that the desired effect, and if so, why?

**Comment by samid737** [comment]
It was too good to be true..... However, prior to this the objects did not rotate at all I think...To me the whole point of passing the rotation as an argument when using addShape is to add A rotated debug geometry, but keeping the sprite its local rotation=0. With this fix it is the case. I did not account for adding shapes within an update however...

Before 2.8.4 (prior fix) there was also another way to fix at least the capsule(deforming incorrectly) and line, but  rectangle and polygon were still in trouble. In drawRectangle, drawRect is called, so the geometry is axis aligned.... The polygon rotates every child polygon aswell...  

The fix for the line and capsule:

    drawLine: function(g, len, color, lineWidth,angle) {

        var c= Math.cos(angle);
        var s= Math.sin(angle);
        
        if (lineWidth === undefined) { lineWidth = 1; }
        if (color === undefined) { color = 0x000000; }

        g.lineStyle(lineWidth * 5, color, 1);
        g.moveTo(-len / 2 *c, 0);//include rotation
        g.lineTo(len / 2 *c, len *s);//include rotation
    },

    //the drawcapsule function
     drawCapsule: function(g, x, y, angle, len, radius, color, fillColor, lineWidth) {

        if (lineWidth === undefined) { lineWidth = 1; }
        if (color === undefined) { color =  0x000000; }

        g.lineStyle(lineWidth, color, 1);

        // Draw circles at ends
        var c = Math.cos(angle);
        var s = Math.sin(angle);

        g.beginFill(fillColor, 1);
        g.drawCircle(-len/2*c + x, -len/2*s + y, -radius * 2);
        g.drawCircle( len/2*c + x,  len/2*s + y, -radius * 2);
        g.endFill();

        // Draw rectangle
        g.lineStyle(lineWidth, color, 0);
        g.beginFill(fillColor, 1);
        g.moveTo(-len/2*c - radius*s + x, -len/2*s + radius*c + y);//reverse signs
        g.lineTo( len/2*c - radius*s + x,  len/2*s + radius*c + y);//reverse signs
        g.lineTo( len/2*c + radius*s + x,  len/2*s - radius*c + y);//reverse signs
        g.lineTo(-len/2*c + radius*s + x, -len/2*s - radius*c + y);//reverse signs
        g.endFill();

        // Draw lines in between
        g.lineStyle(lineWidth, color, 1);
        g.moveTo(-len/2*c - radius*s + x, -len/2*s + radius*c + y);
        g.lineTo( len/2*c - radius*s + x,  len/2*s + radius*c + y);
        g.moveTo(-len/2*c + radius*s + x, -len/2*s - radius*c + y);
        g.lineTo( len/2*c + radius*s + x,  len/2*s - radius*c + y);
    },


The only way I could think of rotating the poly and rectangle was to rotate the global shape..... Perhaps there is another way to approach this?

**Comment by samid737** [comment]
http://www.html5gamedevs.com/topic/32754-polygon-collision-does-not-work/

I can confirm that this happens after 2.8.3.  Demo:

[2.8.3](https://samid737.github.io/258demo1/) 

[2.8.4](https://samid737.github.io/258demo2/) 

Without supplying the rotation argument it will fail to collide.

I think reverting would be more useful then debugging this hack. There is a way to correct the rotation transformations during the debug draws. The following can be considered:

* Line: 

The line can be rotated inside drawLine() :
```
drawLine: function(g, len, color, lineWidth,angle) {

    var c= Math.cos(angle);//include angle
    var s= Math.sin(angle);//include angle
    
    if (lineWidth === undefined) { lineWidth = 1; }
    if (color === undefined) { color = 0x000000; }

    g.lineStyle(lineWidth * 5, color, 1);
    g.moveTo(-len / 2 *c, 0);//include angle
    g.lineTo(len / 2 *c, len *s);//include angle
},
```

* Capsule:

The rectangles inside the capsule where deforming incorrectly, changing +- solves this:
```

 drawCapsule: function(g, x, y, angle, len, radius, color, fillColor, lineWidth) {

    if (lineWidth === undefined) { lineWidth = 1; }
    if (color === undefined) { color =  0x000000; }

    g.lineStyle(lineWidth, color, 1);

    // Draw circles at ends
    var c = Math.cos(angle);
    var s = Math.sin(angle);

    g.beginFill(fillColor, 1);
    g.drawCircle(-len/2*c + x, -len/2*s + y, -radius * 2);
    g.drawCircle( len/2*c + x,  len/2*s + y, -radius * 2);
    g.endFill();

    // Draw rectangle
    g.lineStyle(lineWidth, color, 0);
    g.beginFill(fillColor, 1);
    g.moveTo(-len/2*c - radius*s + x, -len/2*s + radius*c + y);//reverse signs
    g.lineTo( len/2*c - radius*s + x,  len/2*s + radius*c + y);//reverse signs
    g.lineTo( len/2*c + radius*s + x,  len/2*s - radius*c + y);//reverse signs
    g.lineTo(-len/2*c + radius*s + x, -len/2*s - radius*c + y);//reverse signs
    g.endFill();

    // Draw lines in between
    g.lineStyle(lineWidth, color, 1);
    g.moveTo(-len/2*c - radius*s + x, -len/2*s + radius*c + y);//reverse signs
    g.lineTo( len/2*c - radius*s + x,  len/2*s + radius*c + y);//reverse signs
    g.moveTo(-len/2*c + radius*s + x, -len/2*s - radius*c + y);//reverse signs
    g.lineTo( len/2*c + radius*s + x,  len/2*s - radius*c + y);//reverse signs
},
```

* Rectangle:

A solution for the rectangle would be to use lineTo() instead of drawRect() ,this way the rectangle can also be rotated:

```
    drawRectangle: function(g, x, y, angle, w, h, color, fillColor, lineWidth) {

        if (lineWidth === undefined) { lineWidth = 1; }
        if (color === undefined) { color = 0x000000; }
        c=Math.cos(angle);
        s=Math.sin(angle);
        ox= w/2;
        oy=h/2;

        oxc=ox*c;
        oxs=ox*s;

        oyc=oy*c;
        oys=oy*s;

        g.lineStyle(lineWidth, color, 1);
        g.beginFill(fillColor);
        g.moveTo(x+(+oxc-oys),y+(-oxs-oyc));
        g.lineTo(x-(-oxc-oys),y-(oxs-oyc));
        g.lineTo(x+(-oxc+oys),y+(oxs+oyc));
        g.lineTo(x-(oxc+oys),y-(-oxs+oyc));
    },

```

* Polygon:

There is a way  to rotate  the polygon during the debug drawing,  (line 95533):

                    for (j = _j = 0, _ref1 = child.vertices.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j)
                    {
                        v = child.vertices[j];
                        v[0]+=offset[0];
                        v[1]+=offset[1];
                        p2.vec2.rotate(vrot, v, angle);
                        verts.push([(vrot[0])* this.ppu, -(vrot[1]) * this.ppu]);
                    }



however , there is A mismatch with the actual body when doing this, so the polygon is still an issue, which I could not solve. I think it would be better to not rotate polygons (how it originally was).

* Circle:

Already worked.

* [Here is a demo ](https://samid737.github.io/258demo3/)of the above fixes (excluding polygon) in v2.8.3:

I noticed that line->Rectangles and Line->Capsule do not collide in the demo. This also occurs in 2.6.2.

**Pull request merged**
