### PR TITLE
Version 2.7.9 doesn't exist as a CDN

### PR DESCRIPTION
**Pull request by entozoon**
Changed to 2.7.7 in the meantime, which does.

Make sure you describe your PR in the [README Change Log](../README.md#change-log) section!

This PR changes (✏️ delete as applicable)

* Documentation
* TypeScript Defs
* The public-facing API
* Nothing, it's a bug fix

Describe the changes below:

### CODE REVIEW

**Comment by samme** [comment]
@photonstorm should jsDelivr have v2.7.9 by now?

**Comment by photonstorm** [comment]
It doesn't seem to have 2.7.8 either. It seems to fail to get new versions if they are tagged on GitHub directly and not tagged locally then pushed. Either that or they've stopped pulling them.

**Comment by samme** [comment]
These should work once we slim the package down (#214):

<https://cdn.jsdelivr.net/npm/phaser-ce@2.7.9/build/phaser.js>

> Package size exceeded the configured limit of 50 MB.

**Comment by photonstorm** [comment]
Did it grow that much between 2.7.7 and 2.7.8?

**Comment by samme** [comment]
No, it didn't grow, it's only the `/npm/package@version` format URLs that show the "Package size" error (for any phaser-ce version). I guess those URLs draw directly from NPM.

**Comment by photonstorm** [comment]
I don't think the size is the reason it wasn't merged to the CDN then tbh.

**Comment by entozoon** [comment]
How does it merge to the CDN? Just wondering if there's a git hook somewhere that only kicks in when it's tagged and pushed locally. Could be worth a cheeky 2.7.10 tag for the same of updating it?

**Comment by photonstorm** [comment]
Not entirely sure, it is automatic, I've never needed to manually do anything before. Which makes me think it needs a locally committed tag to fire. If you want to release 2.7.10 I'll tag it locally and push. If that doesn't work either the issue is with the CDN.

**Comment by entozoon** [comment]
Hope that's helpful @photonstorm :)

**Comment by MartinKolarik** [comment]
jsDelivr switched to a new backend last week. The old URLs no longer receive updates. The new endpoints `/npm/package@version` and `/gh/user/repo@version` are fully automatic, but have the above mentioned size restriction.

**Comment by samme** [comment]
<http://cdn.jsdelivr.net/npm/phaser-ce@2.7.10/build/phaser.js> 🎉

**Pull request merged**
