### PR TITLE
Removing callback on a tile to null now works as expected

### PR DESCRIPTION
**Pull request by masondesu**
This PR

* is a bug fix

`Phaser.Tilemap#setTileIndexCallback`'s documentation indicates that callbacks can be removed by passing in `null` as the callback argument (see https://github.com/photonstorm/phaser/blob/v2.4.4/src/tilemap/Tilemap.js#L751). However, `Phaser.Physics.Arcade#separateTile` doesn't actually do a null check on the function itself, which results in trying to `call` on `null`. This just adds an additional check to ensure that an actual function is present.

Another possible fix would be to replace the object literal here with `null` at https://github.com/photonstorm/phaser/blob/v2.4.4/src/tilemap/Tilemap.js#L774 in `Phaser.Tilemap#setTileIndexCallback` when the `callback` arg is `null`, but this would still leave `separateTile` trying to `call` something hasn't been checked, which seemed a little less ideal. I could, however, see it either way.

Happy to rework this if y'all think there's a better way to prevent this bug. Thanks a ton!

### CODE REVIEW

**Comment by samme** [comment]
How about removing the callback object with `delete` in Phaser.Tilemap#setTileIndexCallback?

**Comment by masondesu** [comment]
Yo, sorry for the delay, was AFK for a few days. I've followed your suggestion on deleting the callback object. The type check in in `separateTile` is still present. I'm happy to remove it if you think it's no longer relevant, or leave it intact as a precaution. Thanks! :)

**Comment by samme** [comment]
Thanks. I favor removing the type check, as it really should error if the data is bad, and it's very slightly slower.

**Comment by masondesu** [comment]
The commit log is a bit of a mess here with merges and reversions. I'll open a fresh PR with a more reasonable number of commits in just a sec.

**Pull request closed without merging**
