### PR TITLE
creature upgrades for pixel scaling and anchor point setting

### PR DESCRIPTION
**Pull request by andrewjb123**
creature upgrades for pixel scaling and anchor point setting

### CODE REVIEW

**Comment by samme** [comment]
Can you add a note to <https://github.com/photonstorm/phaser-ce/blob/master/README.md#change-log> too?

**Comment by samme** [comment]
Hi @andrewjb123 can you open a new PR that moves all these additions to src/gameobjects/Creature.js only?

**Comment by andrewjb123** [comment]
hi samme, do you still need me to do the above comments done?

The changes which are in the phaser-creature.js / creature.js files shouldn't be moved to the src/gameobjects/Creature.js as these additions are part of the kestrel moon creature runtimes and are committed as part of this runtimes project - all i've done is ported the changes from these issues into your build of creature in the CE branch. _Please advise if this is not the right process for committing changes from the kestrel moon runtimes._

please see change sets of the kestrel moon creature runtimes here which i ported over:

https://github.com/kestrelm/Creature_WebGL/commit/c7bf6199ed33328dbe260811f13871d3185e79a4
https://github.com/kestrelm/Creature_WebGL/commit/e870c00d7b096a13903aa77d0ce8d172be6dd289
https://github.com/kestrelm/Creature_WebGL/commit/184cb4d89c88cb5bd2310ed6afef6d66d9c22c78

**Comment by samme** [comment]
Yes, please, all the Creature changes should go in any of

    src/animation/creature/CreatureMeshBone.js
    src/animation/creature/gl-matrix.js
    src/gameobjects/Creature.js

Anything in build/creature.js will get lost with a new build. Thanks.

**Comment by andrewjb123** [comment]
ok thats been done, pull request is in https://github.com/photonstorm/phaser-ce/pull/202

**Pull request merged**
