### PR TITLE
Add simpler phaser/webpack setup sample

### PR DESCRIPTION
**Pull request by georgesboris**
While the phaser-es6-webpack project works, it contains a lot of boilerplate code that obscures the minimal steps needed for making phaser work with a webpack setup. I've provided a **really** simple gist showing how easy it actually is.

The gist: https://gist.github.com/georgesboris/48e40307243248f2c8890e6f8ae00613

### CODE REVIEW

**Comment by georgesboris** [comment]
I'm actually questioning if this shouldn't just be added in it's entirety to the docs. Since it's so small. It can even be shortened with that in mind.

**Comment by rblopes** [comment]
Please update your PR description to add your Gist link, so other contributors can find it more easily and provide their input.

**Comment by georgesboris** [comment]
@rblopes Sure! 👍

**Comment by samme** [comment]
If you write the equivalent config you can take #95 as well. 😃

**Comment by georgesboris** [comment]
@samme Do you think that updating the webpack project template with the minimal setup needed with comments and such would be a better solution? That way we could just link the template from the readme. (This should be really trivial. Should I update the PR with this changes or should I create another fork?)

**Comment by samme** [comment]
Sure, you can just update this PR.

**Comment by georgesboris** [comment]
@samme I've updated the webpack project template. It is working as expected.

**Pull request merged**
