### PR TITLE
Creature anchor points pixel scaling

### PR DESCRIPTION
**Pull request by andrewjb123**
creature anchor point, pixel scaling implementation from creature
runtimes

### CODE REVIEW

**Comment by samme** [comment]
Hi @andrewjb123, I tried a demo but my creature has `width`, `height`, and `anchorX`/`Y` values undefined: <https://codepen.io/samme/pen/YQajJj>.

**Comment by andrewjb123** [comment]
Hi samme,

If you so creature.width = 50; creature.height = 50, after .play() this will set the height and width - I will look into the anchor problem

**Comment by andrewjb123** [comment]
Sorry and remove scale.set()

**Comment by andrewjb123** [comment]
The same can be done for anchorX/Y

Creature.anchorY = 1; creature.anchorX = 0.5;

I'm away at the moment so don't have laptop with me but when I get back I'll look to put some demos together.

**Comment by andrewjb123** [comment]
dragon = game.add.creature(450, 350, "dragonTexture", "dragonMesh");
  //dragon.scale.set(25.0);
  dragon.setAnchorPointEnabled(true);
  dragon.play(true);
  
  dragon.anchorX = 0.5;
  dragon.anchorY = 0.5;
  
  // Must be after `play`
  dragon.width = 600; //width in debug now 600
  dragon.height = 400;
  // console.log("dragon", dragon);

**Comment by andrewjb123** [comment]
Hi Samme,

I see the demo has been updated and seems to work. Was there anything else i needed to do?

I noticed if you set the anchor points in succession (e.g. 0.5 - 1 - 0.5) it does it moves the anchor relative to the last point.

I think this is maybe a problem in the creature runtime code i pulled in. I guess ideally it firsts needs to be reset to its initial position, and then the new anchor point set.

i only ever set the anchor point once, so never noticed this behaviour, is it worth raising a PR? and either i can look at it when i have time, or someone else can have a go?

Thanks

Andy

**Comment by samme** [comment]
> I noticed if you set the anchor points in succession (e.g. 0.5 - 1 - 0.5) it moves the anchor relative to the last point.

Guess we could either add a note in the docs or open an issue. Depends on whether you consider it a bug or just a limitation. 😃

**Comment by andrewjb123** [comment]
hmmm, i cant see a use case where it would be useful to have relative anchor points, how does phaser do anchor points on sprite objects? if i do sprite.anchor.y = 0.5 and then sprite.anchor.y = 1.0 is the second relative to the first? i guess ideally we should be making behaviour like this consistent, what are your thoughts? 

i guess for now we can add a note to the documentation as this would be the easiest, and im not sure many people use creature with phaser, i think im an edge/head case :)

**Comment by samme** [comment]
<https://codepen.io/samme/pen/Xpbera>

**Comment by andrewjb123** [comment]
i have added a pull request for the relative anchor point problem at #288 

its a potential fix, - it generally works, but i see sometimes the anchor point is misaligned if you set the anchor on x/y too many times.

**Pull request merged**
