### PR TITLE
Updated release version for CDN republish

### PR DESCRIPTION
**Pull request by entozoon**
Updated version to 2.7.10 where needed (Readme,  package, etc)
https://github.com/photonstorm/phaser-ce/pull/222#issuecomment-302050710

### CODE REVIEW

**Comment by photonstorm** [comment]
Have you checked this is < 50MB? :)

**Comment by entozoon** [comment]
Yeah, way less 👍  I can't imagine how it'd hit that limit

**Comment by photonstorm** [comment]
Ok. If you all want a 2.7.10 release then it needs to be packaged properly before I publish it. So update the readme + changelog, republish the docs and defs, and rebuild. Then I can npm publish and tag it (which the cdn will then hopefully pick up). @samme not sure if you want to merge any other changes into 2.7.10 first?

**Comment by samme** [comment]
I can package a new release.

I think the 50MB limit must refer to the uncompressed size of the entire package.

**Comment by photonstorm** [comment]
Yeah, I agree, as the past 2 versions haven't been > 50MB. It must be calculating things differently now.

**Comment by samme** [comment]
Merged in #228, thanks.

**Pull request closed without merging**
